### ISSUE TITLE
Go: run goimports as part of artman script

### ISSUE THREAD

**Issue by jadekler** [googleapis/artman#547] opened 2019-01-10 04:59 UTC
This is currently happening:

- Run artman, which generates something like

    ```
        // somefile.go
        import (
    -       admin "cloud.google.com/go/iam/admin/apiv1"
    +       "cloud.google.com/go/iam/admin/apiv1"
        )
        // doc.go
    +   versionClient=UNKNOWN
    ```
- Run goimports, which turns the import statement _back_ into the following (because the package name does not match the directory name),
    ```
        // somefile.go
        import (
            admin "cloud.google.com/go/iam/admin/apiv1"
        )
        // doc.go
    +   versionClient=UNKNOWN
    ```

So, currently we are ending up with a bunch of versionClient=UNKNOWN churn, causing it to look like packages are getting updated when really nothing got changed. If artman could run `goimports` before trying to figure out where to stick `versionClient`, it would solve our problem.

**Comment by andreamlin** [comment] 2019-01-10 18:04
Can you provide an example PR where `versionClient=UNKNOWN` is generated? I can't seem to find where this would be set in the gapic-generator codebase, and I'm not sure when artman would introduce another string inside of a generated file.

**Comment by vam-google** [comment] 2019-01-10 18:23
This will be fixed in the upcoming Bazel GAPIC generation (Go support is coming soon, probably next week). Bazel generation produces equal to artman output, does not require installation and should be very easy to migrate to from artman. In that case, we can avoid making the enhancement in artman.

**Comment by jadekler** [comment] 2019-01-10 18:35
Er... I'm thoroughly confused, sorry :( How do artman, bazel, and micro generators relate to each other? Is bazel just another driver for artman instead of docker containers, or?

**Comment by vam-google** [comment] 2019-01-10 23:09
@jadekler For our use case, we can think about this as follows:
- Bazel replaces Docker, but unlike Docker "installing" it means just getting single Bazel binary on the machine (there are also supported by the bazel team docker images with the binary already available, for convenience). This does not need root permissions and does not contaminate the system (i.e. does not require system-wide changes).
- Bazel GAPIC Extensions replace artman, with additional funcitonality (unlike artman it not only generates the code, but also compiles and runs the generated tests, thus validating the generated code plus making it ready for use out of the box in bazel-based projects). Similarly to how grpc stubs can be generated and compiled with `<lang>_grpc_library` (like  `go_grpc_library`, java_grpc_library` etc) rules, Bazel GAPIC extensions provide <lang>_gapic_library rules to generate and compile GAPIC clients.
- Microgenerator is a language-specific generator. Specifically, artman now calls the macro gapic-generator (same binary for all 7 languages) to generate the client. Creating client is more work than simply generating it, another operations are: distributing sources in proper folders, code formatting etc (these are the other things that artman/gapic_bazel_exetnsions do, but the generators don't). Artman does not support microgenerators. Bazel extesnions are supposed to support both old (macro) and new (micro) generators, making future migration to microgenerators easy.

**Comment by jadekler** [comment] 2019-01-10 23:53
Ah! Gotcha. Very interesting. How soon is "upcoming", for my edification?

**Comment by noahdietz** [comment] 2019-01-16 22:31
@jadekler to be clear, micro-generator support with Bazel is farther out, but I believe Bazel support for the existing GAPIC generator is coming very soon.

**Comment by jadekler** [comment] 2019-01-21 21:20
Ah - thanks!

**Comment by jadekler** [comment] 2019-02-01 17:50
Friendly ping. This has almost been a month. I understand that the bazel stuff is coming soon (tm), but would it at all be possible to prioritize this enhancement now so that we aren't feeling pain however long the transition takes? It really is quite a nuisance every single time we generate clients.

**Comment by noahdietz** [comment] 2019-02-01 18:01
The Bazel Go support is being [reviewed right now](https://github.com/googleapis/gapic-generator/pull/2526)...so close! :pray: 

@vam-google can you confirm that the work under review right now will help address this issue? Or is there something we need to add to it to get a fix in with the current PR?

**Comment by andreamlin** [comment] 2019-02-01 19:12
@noahdietz I think that we should just do the goimports feature request for artman if it's feasible. Unless Yoshi's synthtool migrates to using bazel soon, it won't matter if the Bazel support for Go is good to go. AFAIK Yoshi still uses artman for java generation even tho we have Bazel Java support.

**Comment by noahdietz** [comment] 2019-02-01 19:18
sgtm! I'll get on it

**Comment by noahdietz** [comment] 2019-02-04 22:06
After some poking around and testing, it doesn't look like usage `goimports` *isn't* the cause of the import naming churn. This can be verified by running `goimports -w language/` from within the `cloud.google.com/go` directory.

I will look at `gapic-generator` for potential miss naming of the package alias.

**Closed** 2019-02-04 23:34 UTC
Labels: enhancement
