### ISSUE TITLE
Artman fails on cloudtasks

### ISSUE THREAD

**Issue by jadekler** [googleapis/artman#520] opened 2018-10-29 15:33 UTC
```
$ $GOPATH/src/cloud.google.com/go/regen-gapic.sh
...
+ cp -r artman-genfiles/gapi-cloud-tasks-go/cloud.google.com/go/cloudtasks /Users/deklerk/workspace/go/src/cloud.google.com/go/
+ for api in '"${APIS[@]}"'
+ rm -rf artman-genfiles/gapi-cloud-tasks-go artman-genfiles/go artman-genfiles/go_google-cloud-tasks-v2beta2_package2.yaml artman-genfiles/google-cloud-tasks-v2beta2.desc
+ artman --config google/cloud/tasks/artman_cloudtasks_v2beta3.yaml generate go_gapic
No artman user config defined. Use the default one for this execution. Run `configure-artman` to set up user config.
artman> Final args:
artman>   api_name: tasks
artman>   api_version: v2beta3
artman>   artifact_type: GAPIC
artman>   aspect: ALL
artman>   gapic_code_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/gapi-cloud-tasks-go
artman>   gapic_yaml: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/tasks/v2beta3/cloudtasks_gapic.yaml
artman>   import_proto_path:
artman>     - /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis
artman>   language: go
artman>   organization_name: google-cloud
artman>   output_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles
artman>   proto_deps:
artman>     - name: google-common-protos
artman>   root_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis
artman>   service_yaml: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/tasks/cloudtasks_v2beta3.yaml
artman>   src_proto_path:
artman>     - /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/tasks/v2beta3
artman>   toolkit_path: ''
artman>
artman> Running artman command in a Docker instance.
artman> artman> Final args:
artman>   api_name: tasks
artman>   api_version: v2beta3
artman>   artifact_type: GAPIC
artman>   aspect: ALL
artman>   gapic_code_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/gapi-cloud-tasks-go
artman>   gapic_yaml: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/tasks/v2beta3/cloudtasks_gapic.yaml
artman>   import_proto_path:
artman>     - /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis
artman>   language: go
artman>   organization_name: google-cloud
artman>   output_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles
artman>   proto_deps:
artman>     - name: google-common-protos
artman>   root_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis
artman>   service_yaml: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/tasks/cloudtasks_v2beta3.yaml
artman>   src_proto_path:
artman>     - /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/tasks/v2beta3
artman>   toolkit_path: /toolkit
artman>
artman> Creating GapicClientPipeline.
artman.output >
Missing input file.

artman> Traceback (most recent call last):
  File "/artman/artman/cli/main.py", line 71, in main
    engine.run()
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 159, in run
    for _state in self.run_iter():
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 223, in run_iter
    failure.Failure.reraise_if_any(it)
  File "/usr/local/lib/python3.5/dist-packages/taskflow/types/failure.py", line 292, in reraise_if_any
    failures[0].reraise()
  File "/usr/local/lib/python3.5/dist-packages/taskflow/types/failure.py", line 299, in reraise
    six.reraise(*self._exc_info)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/executor.py", line 82, in _execute_task
    result = task.execute(**arguments)
  File "/artman/artman/tasks/protoc_tasks.py", line 57, in execute
    desc_protos)
  File "/artman/artman/tasks/task_base.py", line 64, in exec_command
    raise e
  File "/artman/artman/tasks/task_base.py", line 56, in exec_command
    output = subprocess.check_output(args, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['protoc', '--proto_path=/Users/deklerk/workspace/go/src/github.com/googleapis/googleapis', '--proto_path=/Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/tasks/v2beta3', '--proto_path=/toolkit/build/toolpaths/protobufJavaDir', '--include_imports', '--include_source_info', '-o', '/Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/google-cloud-tasks-v2beta3.desc']' returned non-zero exit status 1


artman> Artman execution failed. For additional logging, re-run the command with the "--verbose" flag
```

**Comment by alexander-fenster** [comment] 2018-10-29 16:23
FYI: it works in CI. https://circleci.com/gh/googleapis/googleapis/1399

![image](https://user-images.githubusercontent.com/4015807/47664423-3f48a600-db5c-11e8-8523-e9bf04c00604.png)

I will try reproducing locally.

**Comment by alexander-fenster** [comment] 2018-10-29 16:56
As discussed - looks like it was caused by local misconfiguration since running `configure-artman` helped. Closing the issue.

**Closed by alexander-fenster** 2018-10-29 16:56 UTC
